name: Justsay Server CI
on:
  push:
    branches: [ main ] 
 
  # 이부분은 위의 trigger가 없어도 수동으로 동작 할 수 있게끔 해주는 역할을 합니다.
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build" 
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout release
      uses: actions/checkout@v3

    - name: archive drcloud 
      run: tar cvfz ./justsay-server.tar.gz *
       
    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./justsay-server.tar.gz s3://justsay-server-deploy/archive/
      
    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name justsay-server
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name justsay-server-group
        --s3-location bucket=justsay-server-deploy,bundleType=tgz,key=archive/justsay-server.tar.gz
